### PR TITLE
NWPS-792 Applies to box

### PR DESCRIPTION
**Pull request by FranciscoRuizHEE**
Creation of  Applies to Box component. It is a text to specify where to applies England, Scotland, Wales or Northern Ireland. This could be customized by the editors.

### CODE REVIEW

**Comment by smanivasag** [comment]
Hi @FranciscoRuizHEE - Could we get rid of template queries other than the ones (`repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-appliesToBox-folder.yaml` & `repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-appliesToBox-document.yaml`) related to this ticket ? (I guess you would have pressed `Generate All` button on `Template Query Generator tool` on `Essentials` which would have led to this)

**Comment by smanivasag** [comment]
Hi @FranciscoRuizHEE - Have made couple of commits 7603c2142ba855e8d5a09f79ca3ad5a88e9ffe38 and ab45c90316e7a4cb1cca533b46bb46880a545fb1. Could you review them ? Thanks!

**Comment by smanivasag** [comment]
Hi @FranciscoRuizHEE - Have made a couple of commits eb6aaf13e6b2af31bd0cee63ea9e8e3972590785 (Implementation of `hee:appliesToCountry` CompoundType to optimise and scale (in the future if required) `hee:appliesToBox` DocumentType) & 43a74ea3da1d8f812200894565293c9bbedc263e (Validation implementation [to check for `hee:linkURL` when `hee:appliesTo` is not checked] for `hee:appliesToCountry` CompoundType). Could you review ? Thanks!

**Review by FranciscoRuizHEE — COMMENTED** [review]
All good

**Pull request merged**
